name: Publish (Manual)

on:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore
        run: make restore
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Pack
        run: make package
      
      - name: Install SBOM tool
        run: dotnet tool install --global Microsoft.Sbom.DotNetTool || true
      
      - name: Generate SBOM
        run: |
          mkdir -p artifacts/sbom
          sbom-tool generate -b artifacts -bc . -pn Flowrex -pv 0.1.0 -ps Gurame -nsb https://github.com/gurame/Flowrex -m artifacts/sbom
      
      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg
          if-no-files-found: error
      
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: artifacts/sbom
          if-no-files-found: warn
  
  publish:
    needs: pack
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Download NuGet packages
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: artifacts
      
      - name: Publish to NuGet
        run: |
          dotnet nuget push artifacts/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
