name: Security

on:
  # Run security checks weekly
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Mondays at 3am UTC

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      DOTNET_NUGET_SIGNATURE_VERIFICATION: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Security checks
        run: make ci-security
